version: 2.1
orbs:
  aws-cli: circleci/aws-cli@4.1.1
  terraform: circleci/terraform@3.2.1

executors:
  docker-executor:
    docker:
      - image: cimg/node:20.5.0 

jobs:
  tfplan:
    parameters:
      role_arn:
        type: string
      region:
        type: string 
    executor: docker-executor
    environment:
      TF_VAR_region: <<parameters.region>>
      TF_VAR_role_arn: <<parameters.role_arn>>
    steps:
      - checkout
      - terraform/install:
          arch: amd64
          os: linux
          terraform_version: 1.5.7
      - aws-cli/setup
      - aws-cli/role_arn_setup:
          profile_name: tfdemo
          role_arn: <<parameters.role_arn>>
          source_profile: default
      #- run: aws sts get-caller-identity
      - run: printenv
      - run:
          name: Infra Creation/Terraform Plan
          command: |
            terraform init -backend-config="key=tfdemo/terraform.tfstate"
            terraform plan -var-file="dev.tfvars" -out tfapply
  tfapply:
    parameters:
      role_arn:
        type: string
      region:
        type: string
    executor: docker-executor
    environment:
      TF_VAR_region: <<parameters.region>>
      TF_VAR_role_arn: <<parameters.role_arn>>
    steps:
      - terraform/install:
          arch: amd64
          os: linux
          terraform_version: 1.5.7
      - aws-cli/setup
      - aws-cli/role_arn_setup:
          profile_name: tfdemo
          role_arn: <<parameters.role_arn>>
          source_profile: default
      #- run: aws sts get-caller-identity
      # - run: printenv
      - run:
          name: Infra Creation/Terraform Apply
          command: | 
            terraform init -backend-config="key=tfdemo/terraform.tfstate"
            terraform plan -var-file="dev.tfvars" -out tfapply
            terraform apply -auto-approve tfapply
            



workflows:
  IAC:
    jobs:
    - tfplan: 
        context: 
          - cicd-context
        region: us-east-1
        role_arn: arn:aws:iam::312552815388:role/CICD
    - tfapply_approval:
        type: approval
        requires:
          - tfplan
    - tfapply:  # This job runs after approval
        context: 
          - cicd-context
        region: us-east-1
        role_arn: arn:aws:iam::312552815388:role/CICD
        requires:
          - tfapply_approval


